package com.lumecard.shared.data

import com.lumecard.shared.data.ai.AiFallbackManager
import com.lumecard.shared.data.ai.ProviderAdapter
import com.lumecard.shared.model.Card
import com.lumecard.shared.model.CardType
import com.lumecard.shared.model.Deck
import com.lumecard.shared.model.KnowledgeBase
import com.lumecard.shared.repository.CardRepository
import com.lumecard.shared.repository.DeckRepository
import com.lumecard.shared.repository.KnowledgeBaseRepository
import kotlinx.serialization.json.Json
import kotlin.time.Clock
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

class AiCardGenerator(
    private val adapter: ProviderAdapter,
    private val fallbackManager: AiFallbackManager,
    private val promptManager: AiCardPromptManager,
    private val knowledgeBaseRepository: KnowledgeBaseRepository,
    private val deckRepository: DeckRepository,
    private val cardRepository: CardRepository,
) {
    private val json = Json { ignoreUnknownKeys = true }

    @OptIn(ExperimentalUuidApi::class)
    suspend fun generate(request: AiCardRequest): Result<AiCardResult> {
        return try {
            val promptTemplate = promptManager.getActivePrompt()
            val systemPrompt = promptTemplate.replace("{card_count}", request.cardCount.toString())
            val userMessage = buildUserMessage(request)

            val response = fallbackManager.sendWithFallback(
                config = request.config,
                systemPrompt = systemPrompt,
                userMessage = userMessage,
            )

            val content = response.getOrElse { e ->
                val msg = e.message ?: ""
                val aiErr = when {
                    msg.contains("401") -> AiCardException(AiCardError.AUTH_FAILED, msg)
                    msg.contains("429") -> AiCardException(AiCardError.RATE_LIMITED, msg)
                    msg.contains("Timeout", ignoreCase = true) -> AiCardException(AiCardError.TIMEOUT, msg)
                    msg.contains("Connection") -> AiCardException(AiCardError.CONNECTION_FAILED, msg)
                    msg.contains("Parse error", ignoreCase = true) -> AiCardException(AiCardError.PARSE_ERROR, msg)
                    else -> AiCardException(AiCardError.API_ERROR, msg)
                }
                return Result.failure(aiErr)
            }

            val parsed = try {
                json.decodeFromString<AiCardResponseJson>(content)
            } catch (e: Exception) {
                return Result.failure(
                    AiCardException(AiCardError.PARSE_ERROR, "Failed to parse AI response as JSON: ${e.message}")
                )
            }

            if (parsed.cards.isEmpty()) {
                return Result.failure(
                    AiCardException(AiCardError.NO_CONTENT, "AI returned no cards")
                )
            }

            val (kbId, deckId) = resolveEntities(request, parsed)
            val cardIds = createCards(deckId, parsed)

            Result.success(
                AiCardResult(
                    knowledgeBaseName = parsed.knowledge_base_name.ifBlank { request.knowledgeBaseName ?: "AI Cards" },
                    deckName = parsed.deck_name.ifBlank { request.deckName ?: "AI Cards" },
                    knowledgeBaseId = kbId,
                    deckId = deckId,
                    cardsCreated = cardIds.size,
                    cardIds = cardIds,
                )
            )
        } catch (e: AiCardException) {
            Result.failure(e)
        } catch (e: Exception) {
            Result.failure(
                AiCardException(AiCardError.UNKNOWN, "Unexpected error: ${e.message}")
            )
        }
    }

    private fun buildUserMessage(request: AiCardRequest): String {
        val sb = StringBuilder()
        sb.appendLine("Generate ${request.cardCount} flashcards.")
        sb.appendLine()
        sb.appendLine("Topic / Goal:")
        sb.appendLine(request.topic)
        when (request.mode) {
            AiCardMode.AUTO, AiCardMode.SPECIFY_KB -> {
                sb.appendLine()
                sb.appendLine("Create a knowledge base and deck with appropriate names.")
            }
            AiCardMode.SPECIFY_BOTH -> {}
        }
        if (request.referenceMaterials.isNotBlank()) {
            sb.appendLine()
            sb.appendLine("Reference materials:")
            sb.appendLine(request.referenceMaterials)
        }
        return sb.toString()
    }

    @OptIn(ExperimentalUuidApi::class)
    private suspend fun resolveEntities(request: AiCardRequest, parsed: AiCardResponseJson): Pair<String, String> {
        return when (request.mode) {
            AiCardMode.AUTO -> {
                val kbName = makeUniqueKbName(parsed.knowledge_base_name.ifBlank { "AI Cards" })
                val kb = KnowledgeBase(
                    id = "kb_${Uuid.random().toString().take(8)}",
                    name = kbName,
                    description = "Auto-generated by AI",
                    createdAt = Clock.System.now(),
                    updatedAt = Clock.System.now(),
                )
                knowledgeBaseRepository.insert(kb)

                val deckName = makeUniqueDeckName(kb.id, parsed.deck_name.ifBlank { "Cards" })
                val deck = Deck(
                    id = "deck_${Uuid.random().toString().take(8)}",
                    knowledgeBaseId = kb.id,
                    name = deckName,
                    description = "Auto-generated by AI",
                    createdAt = Clock.System.now(),
                    updatedAt = Clock.System.now(),
                )
                deckRepository.insert(deck)
                Pair(kb.id, deck.id)
            }

            AiCardMode.SPECIFY_KB -> {
                val kbId = request.knowledgeBaseId
                    ?: throw AiCardException(AiCardError.UNKNOWN, "KnowledgeBase ID required")
                val deckName = makeUniqueDeckName(kbId, parsed.deck_name.ifBlank { "Cards" })
                val deck = Deck(
                    id = "deck_${Uuid.random().toString().take(8)}",
                    knowledgeBaseId = kbId,
                    name = deckName,
                    description = "Auto-generated by AI",
                    createdAt = Clock.System.now(),
                    updatedAt = Clock.System.now(),
                )
                deckRepository.insert(deck)
                Pair(kbId, deck.id)
            }

            AiCardMode.SPECIFY_BOTH -> {
                val deckId = request.deckId
                    ?: throw AiCardException(AiCardError.UNKNOWN, "Deck ID required")
                val kbId = request.knowledgeBaseId
                    ?: throw AiCardException(AiCardError.UNKNOWN, "KnowledgeBase ID required")
                Pair(kbId, deckId)
            }
        }
    }

    @OptIn(ExperimentalUuidApi::class)
    private suspend fun createCards(deckId: String, parsed: AiCardResponseJson): List<String> {
        val ids = mutableListOf<String>()
        val now = Clock.System.now()
        for (item in parsed.cards) {
            val cardType = parseCardType(item.type)
            val card = Card(
                id = Uuid.random().toString(),
                deckId = deckId,
                type = cardType,
                front = item.front,
                back = item.back,
                tags = item.tags,
                createdAt = now,
                updatedAt = now,
            )
            cardRepository.insert(card)
            ids.add(card.id)
        }
        return ids
    }

    private fun parseCardType(type: String): CardType {
        return try {
            CardType.valueOf(type.uppercase())
        } catch (_: IllegalArgumentException) {
            CardType.BASIC
        }
    }

    private suspend fun makeUniqueKbName(baseName: String): String {
        val existing = knowledgeBaseRepository.getByName(baseName)
        if (existing == null) return baseName
        var suffix = 1
        while (true) {
            val candidate = "$baseName ($suffix)"
            if (knowledgeBaseRepository.getByName(candidate) == null) return candidate
            suffix++
        }
    }

    private suspend fun makeUniqueDeckName(kbId: String, baseName: String): String {
        val existing = deckRepository.getByNameInKnowledgeBase(kbId, baseName)
        if (existing == null) return baseName
        var suffix = 1
        while (true) {
            val candidate = "$baseName ($suffix)"
            if (deckRepository.getByNameInKnowledgeBase(kbId, candidate) == null) return candidate
            suffix++
        }
    }
}
